spring.application.name=ganesha.ingest

# Kafka Configuration
kafka.bootstrap-servers=localhost:9092
kafka.producer.acks=all
kafka.producer.retries=0
kafka.producer.linger-ms=1
kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
kafka.producer.value-serializer=com.ganesha.ingest.kafka.JsonSerializer
kafka.topics.ingest-events=ingest-events

# Logging Configuration
logging.file.name=logs/ganesha-ingest.log
logging.level.root=INFO
logging.level.com.ganesha=DEBUG
